# PostgreSQL
spring.datasource.url=${DB.URL}
spring.datasource.username=${DB.USERNAME}
spring.datasource.password=${DB.PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}
# CORS
allowed.origin.local=${ALLOWED_ORIGIN_LOCAL}
allowed.origin.prod=${ALLOWED_ORIGIN_PROD}