# App
spring.application.name=taskmanager

# JPA shared
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.config.import=optional:file:.env[.properties]

server.port=${PORT:8080}